service: chris-api-proxy

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  stage: dev
  environment:
    NODE_ENV: production
    AWS_REGION: us-east-1
    TABLE_NAME: chris-dev-users
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:Scan
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: 
            - "arn:aws:dynamodb:us-east-1:*:table/chris-dev-users"

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
      - http:
          path: /
          method: ANY
          cors: true

package:
  exclude:
    - src/**
    - "*.ts"
    - tsconfig.json
    - README.md
    - .git/**